"""Standalone CPU perceptual-metric backend.

SSIMULACRA2 and Butteraugli are reference command-line tools for *images*,
not video filters.  This adapter gives them lossless PNG pairs generated by
one sequential FFmpeg pass per comparison.  The temporary directory exists
only for the lifetime of the task; no feature-length image sequence is kept
in the project or result cache.
"""
from __future__ import annotations

import contextlib
import os
import re
import shutil
import subprocess
import tempfile
import threading
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from vmaf_app.core import proc as proc_util
from vmaf_app.core.analysis_request import AnalysisRequest, MetricRequestSpec
from vmaf_app.core.comparison_recipe import ComparisonRecipe
from vmaf_app.core.crop_detect import CropDetectCancelled, detect_crop, detect_pair
from vmaf_app.core.ffmpeg_locate import ffmpeg_path
from vmaf_app.core.metric_results import FrameMetricResult, MetricProvenance, MetricResultSet
from vmaf_app.core.models import CropBox, CropMode, ScaleDirection, VideoInfo
from vmaf_app.core.process_control import ProcessHandle

BACKEND_ID = "perceptual"
_NUMBER = re.compile(r"(?<![\w.])([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)")


class PerceptualRunError(RuntimeError):
    """A recoverable failure from the standalone perceptual metric backend."""

    def __init__(self, message: str, stderr_tail: str = "") -> None:
        super().__init__(message)
        self.stderr_tail = stderr_tail


class PerceptualCancelled(RuntimeError):  # noqa: N818 - mirrors the established runner exception
    """The caller cancelled a perceptual metric task."""


@dataclass(frozen=True, slots=True)
class PerceptualTaskOutput:
    metrics: MetricResultSet
    source_crop: CropBox | None
    distorted_crop: CropBox | None
    compared_frame_count: int


def find_metric_executable(metric: str) -> str | None:
    """Find the bundled or explicitly configured reference CLI.

    Environment overrides keep this optional tooling out of app settings and
    make CI/fake executable tests deterministic: ``SSIMULACRA2_PATH`` and
    ``BUTTERAUGLI_PATH``.  Packaged builds ship the official static libjxl
    tools, so a normal user does not need to install either executable.
    """
    if metric not in {"ssimulacra2", "butteraugli"}:
        raise KeyError(metric)
    override = os.environ.get(f"{metric.upper()}_PATH", "").strip()
    if override:
        return override if Path(override).exists() else None
    bundled_names = {
        "ssimulacra2": ("ssimulacra2.exe", "ssimulacra2"),
        # libjxl names the CLI butteraugli_main; accept the short name for
        # user-provided installations as well.
        "butteraugli": ("butteraugli_main.exe", "butteraugli.exe", "butteraugli_main", "butteraugli"),
    }[metric]
    bundled_dir = Path(__file__).resolve().parents[1] / "tools" / "libjxl"
    for name in bundled_names:
        candidate = bundled_dir / name
        if candidate.is_file():
            return str(candidate)
    for name in bundled_names:
        on_path = shutil.which(name)
        if on_path:
            return on_path
    return None


def _tool_version(executable: str) -> str:
    for arg in ("--version", "-version", "-V"):
        try:
            completed = proc_util.run([executable, arg], capture_output=True, text=True, timeout=5)
        except OSError:
            return "unknown"
        if completed.returncode == 0:
            line = (completed.stdout or completed.stderr or "").strip().splitlines()
            return line[0][:160] if line else "unknown"
    return "unknown"


def _implementation_version(executable: str) -> str:
    """Prefer the bundled release manifest when a CLI omits its version flag."""
    version = _tool_version(executable)
    bundled_dir = (Path(__file__).resolve().parents[1] / "tools" / "libjxl").resolve()
    try:
        is_bundled = Path(executable).resolve().parent == bundled_dir
    except OSError:
        is_bundled = False
    if version == "unknown" and is_bundled:
        manifest = bundled_dir / "LIBJXL-VERSION.txt"
        if manifest.is_file():
            return manifest.read_text(encoding="utf-8").splitlines()[0].strip()
    return version


def _resolve_crops(
    source: VideoInfo, distorted: VideoInfo, recipe: ComparisonRecipe,
    cancel_event: threading.Event | None, process_handle: ProcessHandle | None,
    on_status: Callable[[str], None] | None,
) -> tuple[CropBox | None, CropBox | None]:
    if recipe.crop_mode is CropMode.NONE:
        return None, None
    if recipe.crop_mode is CropMode.MANUAL:
        return recipe.manual_source_crop, recipe.manual_distorted_crop
    try:
        if on_status:
            on_status("Detecting black bars for perceptual metrics…")
        # Crop detection samples representative windows across the whole
        # file. A short score-duration limit may land entirely in a dark
        # intro and must not define the crop used for the comparison.
        return detect_pair(
            lambda: detect_crop(source, cancel_event=cancel_event, process_handle=process_handle),
            lambda: detect_crop(distorted, cancel_event=cancel_event, process_handle=process_handle),
        )
    except CropDetectCancelled as exc:
        raise PerceptualCancelled("Cancelled by user") from exc


def _content_size(info: VideoInfo, crop: CropBox | None) -> tuple[int, int]:
    return (crop.w, crop.h) if crop else (info.width, info.height)


def _validate_pair(source: VideoInfo, distorted: VideoInfo, recipe: ComparisonRecipe) -> None:
    if source.is_variable_frame_rate or distorted.is_variable_frame_rate:
        raise PerceptualRunError("Variable-frame-rate video is not supported safely yet.")
    fps_tolerance = max(0.01, max(source.fps, distorted.fps) * 0.001)
    if abs(source.fps - distorted.fps) > fps_tolerance:
        raise PerceptualRunError(f"Frame rates do not match ({source.fps:.3f} vs {distorted.fps:.3f} fps).")
    if recipe.duration_limit > 0 and min(source.duration, distorted.duration) + 0.1 < recipe.duration_limit:
        raise PerceptualRunError("The duration limit extends beyond the end of one of the videos.")


def _crop_filter(crop: CropBox | None, info: VideoInfo) -> list[str]:
    if crop is None or crop.is_noop(info.width, info.height):
        return []
    return [crop.as_filter()]


def _image_filtergraph(
    source: VideoInfo, distorted: VideoInfo, recipe: ComparisonRecipe,
    source_crop: CropBox | None, distorted_crop: CropBox | None, step: int,
) -> str:
    """Return two lossless, identically sized RGB48 image streams.

    RGB48 avoids JPEG and 8-bit intermediate losses.  The command uses a
    single decoder pass for each input, then both requested image metrics use
    each resulting pair, so adding Butteraugli to SSIMULACRA2 does not decode
    the videos again.
    """
    source_size = _content_size(source, source_crop)
    distorted_size = _content_size(distorted, distorted_crop)
    if source_size != distorted_size:
        if recipe.scale_direction is ScaleDirection.DISTORTED_TO_SOURCE:
            distorted_target, source_target = source_size, None
        else:
            distorted_target, source_target = None, distorted_size
    else:
        distorted_target = source_target = None

    def chain(input_label: str, output_label: str, crop: CropBox | None, info: VideoInfo, target: tuple[int, int] | None) -> str:
        ops = _crop_filter(crop, info)
        if target is not None:
            ops.append(f"scale={target[0]}:{target[1]}:flags={recipe.scale_algorithm}")
        # select keeps a generic sampling axis distinct from FFmpeg/libvmaf.
        if step > 1:
            ops.append(f"select=not(mod(n\\,{step}))")
        ops += ["setpts=PTS-STARTPTS", "format=rgb48le"]
        return f"[{input_label}]{','.join(ops)}[{output_label}]"

    return ";".join((
        chain("0:v", "distorted", distorted_crop, distorted, distorted_target),
        chain("1:v", "reference", source_crop, source, source_target),
    ))


def _extract_png_pairs(
    source: VideoInfo, distorted: VideoInfo, recipe: ComparisonRecipe,
    source_crop: CropBox | None, distorted_crop: CropBox | None, step: int,
    directory: Path, cancel_event: threading.Event | None,
    process_handle: ProcessHandle | None,
) -> tuple[list[Path], list[Path]]:
    graph = _image_filtergraph(source, distorted, recipe, source_crop, distorted_crop, step)
    reference_pattern = directory / "reference-%08d.png"
    distorted_pattern = directory / "test-%08d.png"
    cmd = [ffmpeg_path(), "-nostdin", "-hide_banner", "-y", "-i", str(distorted.path.resolve()),
           "-i", str(source.path.resolve()), "-filter_complex", graph]
    output_args = ["-fps_mode", "passthrough", "-pix_fmt", "rgb48le"]
    if recipe.duration_limit > 0:
        output_args = ["-t", f"{recipe.duration_limit:.3f}", *output_args]
    cmd += ["-map", "[distorted]", *output_args, str(distorted_pattern)]
    cmd += ["-map", "[reference]", *output_args, str(reference_pattern)]
    if cancel_event is not None and cancel_event.is_set():
        raise PerceptualCancelled("Cancelled by user")
    # A long FFmpeg extraction can write enough diagnostics to fill a pipe.
    # We do not need its progress stream here, so inherit neither pipe and
    # avoid deadlocking a feature-length task before it creates a frame.
    process = proc_util.popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True)
    if process_handle is not None:
        process_handle.attach(process.pid)
    try:
        while process.poll() is None:
            if cancel_event is not None and cancel_event.is_set():
                process.terminate()
                raise PerceptualCancelled("Cancelled by user")
            with contextlib.suppress(subprocess.TimeoutExpired):
                process.wait(timeout=0.1)
    except PerceptualCancelled:
        process.wait(timeout=5)
        raise
    finally:
        if process_handle is not None:
            process_handle.detach(process.pid)
    if process.returncode != 0:
        raise PerceptualRunError("FFmpeg could not prepare lossless perceptual-metric frames.")
    references = sorted(directory.glob("reference-*.png"))
    tests = sorted(directory.glob("test-*.png"))
    # Each output runs to its own input's end, so a pair a frame or two
    # apart leaves extra images on one side. The comparison is the frames
    # both have, as libvmaf scores it (framesync with shortest=1).
    count = min(len(references), len(tests))
    if count == 0:
        raise PerceptualRunError("FFmpeg produced no frame pairs for perceptual metrics.")
    for extra in references[count:] + tests[count:]:
        extra.unlink(missing_ok=True)
    return references[:count], tests[:count]


def parse_score(metric: str, output: str) -> float:
    """Extract the scalar reference-tool score from normal text output."""
    values = _NUMBER.findall(output)
    if not values:
        raise PerceptualRunError(f"{metric} did not produce a numeric score: {output.strip()[:300]}")
    try:
        return float(values[-1])
    except ValueError as exc:
        raise PerceptualRunError(f"Could not parse {metric} score.") from exc


def _run_metric(executable: str, metric: str, reference: Path, test: Path) -> float:
    try:
        completed = proc_util.run([executable, str(reference), str(test)], capture_output=True, text=True, timeout=120)
    except OSError as exc:
        raise PerceptualRunError(f"Could not run {metric}: {exc}") from exc
    combined = (completed.stdout or "") + "\n" + (completed.stderr or "")
    if completed.returncode != 0:
        raise PerceptualRunError(f"{metric} failed for a frame.", combined[-2000:])
    return parse_score(metric, combined)


def run_perceptual_task(
    source: VideoInfo, distorted: VideoInfo, request: AnalysisRequest,
    specs: tuple[MetricRequestSpec, ...], *,
    on_progress: Callable[[int, int, float], None] | None = None,
    on_status: Callable[[str], None] | None = None,
    cancel_event: threading.Event | None = None,
    process_handle: ProcessHandle | None = None,
    resolved_crops: tuple[CropBox | None, CropBox | None] | None = None,
) -> PerceptualTaskOutput:
    """Execute the CPU reference implementation and return independent frame results."""
    if not specs or any(spec.backend_id != BACKEND_ID for spec in specs):
        raise ValueError("perceptual task requires perceptual metric specs")
    if request.recipe.resample_test is not None:
        raise PerceptualRunError("Perceptual CPU metrics do not support resolution round-trip tests yet.")
    _validate_pair(source, distorted, request.recipe)
    executables: dict[str, str] = {}
    for spec in specs:
        executable = find_metric_executable(spec.key)
        if executable is None:
            raise PerceptualRunError(
                f"{spec.key} is not installed. Install the reference {spec.key} executable "
                f"or set {spec.key.upper()}_PATH."
            )
        executables[spec.key] = executable
    steps = {spec.coverage.step if spec.coverage is not None else 1 for spec in specs}
    if len(steps) != 1:
        raise PerceptualRunError("Perceptual metrics in one task must use the same frame coverage.")
    step = steps.pop()
    source_crop, distorted_crop = resolved_crops or _resolve_crops(
        source, distorted, request.recipe, cancel_event, process_handle, on_status
    )
    if on_status:
        on_status("Preparing lossless frames for CPU perceptual metrics…")
    with tempfile.TemporaryDirectory(prefix="videometricslab-perceptual-") as temp:
        references, tests = _extract_png_pairs(
            source, distorted, request.recipe, source_crop, distorted_crop, step,
            Path(temp), cancel_event, process_handle,
        )
        values = {spec.key: [] for spec in specs}
        total = len(references)
        for index, (reference, test) in enumerate(zip(references, tests, strict=True), start=1):
            if cancel_event is not None and cancel_event.is_set():
                raise PerceptualCancelled("Cancelled by user")
            try:
                for spec in specs:
                    values[spec.key].append(_run_metric(executables[spec.key], spec.key, reference, test))
            finally:
                # The image pair is no longer useful after every selected
                # still-image tool consumed it. Keep the temporary peak as
                # low as this batch-oriented FFmpeg bridge permits.
                reference.unlink(missing_ok=True)
                test.unlink(missing_ok=True)
            if on_progress:
                on_progress(index * step, total * step, 0.0)
    frame = np.arange(total, dtype=np.int32) * step
    time = frame.astype(np.float64) / max(source.fps, 1.0)
    results = MetricResultSet()
    for spec in specs:
        version = _implementation_version(executables[spec.key])
        compatibility = f"{spec.key}-libjxl-cpu-v1"
        results.add(FrameMetricResult(
            spec.key, frame, time, np.asarray(values[spec.key], dtype=np.float32),
            MetricProvenance(
                implementation=spec.key,
                implementation_version=version,
                compute_backend="cpu",
                implementation_compatibility_id=compatibility,
                parameters={"intermediate": "png/rgb48le", "coverage_step": step},
            ),
        ))
    return PerceptualTaskOutput(results, source_crop, distorted_crop, total * step)
