"""Compiles native/amf_handover.slang (amf_frames.cpp's picture hand-over)
to SPIR-V, both sample sizes, into native/amf_handover_spv.h, which is
committed: building amf_frames.dll (scripts/build_gpu_frames.ps1) needs only
g++. Run after changing the shader:

    python scripts/build_amf_shader.py --slangc <path to slangc.exe>

Slang 2026.10.2 (https://github.com/shader-slang/slang/releases), the version
the committed header was made with.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "native" / "amf_handover.slang"
OUTPUT = ROOT / "native" / "amf_handover_spv.h"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--slangc", required=True, type=Path)
    args = parser.parse_args()
    lines = ["// Generated by scripts/build_amf_shader.py from native/amf_handover.slang: do not edit.",
             "#pragma once", "#include <stdint.h>", ""]
    with tempfile.TemporaryDirectory() as folder:
        for bits in (8, 16):
            spirv = Path(folder) / f"handover{bits}.spv"
            subprocess.run([str(args.slangc), str(SOURCE), "-target", "spirv", "-profile", "spirv_1_3", "-entry", "main",
                            "-stage", "compute", "-O2", f"-DBITS={bits}", "-o", str(spirv)], check=True)
            data = spirv.read_bytes()
            words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
            lines.append(f"static const uint32_t kHandoverSpirv{bits}[] = {{")
            lines += ["    " + ", ".join(f"0x{word:08x}" for word in words[i:i + 8]) + ","
                      for i in range(0, len(words), 8)]
            lines += ["};", ""]
    OUTPUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"{OUTPUT.relative_to(ROOT)}: {OUTPUT.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
